jobs:
  prod-regression:
    <<: *docker_images
    <<: *working_directory
    steps:
      - install
      - run:
          command: ENV=prod npx wdio --suite prodRegression;

workflows:
  version: 2
  Prod Regression:
    jobs:
      - prod-regression:
          filters:
            branches:
              only:
                - prod # Branch name on which the job needs to be executed
