jobs:
  sanity:
    <<: *docker_images
    <<: *working_directory
    steps:
      - install
      - run:
          command: ENV=stage npx wdio --suite sanity

workflows:
  version: 2
  Sanity:
    jobs:
      - sanity:
          filters:
            branches:
              ignore: # List of branches on which the job should not run
                - master
                - staging
