jobs:
  sanity:
    <<: *docker_images
    <<: *working_directory
    steps:
      - install
      - run:
          command: ENV=stage npx wdio --suite sanity
      - store_artifacts:
          path: ~/ll-automation/reports/

workflows:
  version: 2
  Sanity:
    jobs:
      - sanity:
          filters:
            branches:
              only:
                - sanity # Branch name on which the job needs to be executed

